name = "robot"
workers_dev = true
# account_id = ""
# route = ""
# usage_model = "bundled"
compatibility_flags = []
compatibility_date = ""

[build]
# command = "pnpm run build"
cwd = "./src"
watch_dir = "./src"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]
